# action.yml
name: 'License checker'
description: 'Check the licenses found.'
inputs:
  licenses_file:
    description: 'The JSON licenses file to examine.'
    required: false
    default: 'licenses.json'
outputs:
  unapproved_licenses:
    description: '(bool) Whether or not unapproved licenses were found.'
runs:
  using: 'docker'
  # image: 'Dockerfile'
  image: ghcr.io/oracledevrel/license_audit:latest
    credentials:
      username: ${{ github.actor }}
      password: ${{ secrets.GHCR_PAT }}
  args:
    - ${{ inputs.license_file }}