# Copyright (c) 2021 Oracle and/or its affiliates.

# action.yml
name: 'Git Files Changed'
description: 'Look at the files changed in git commits.'
inputs:
  number_commits_back:
    description: 'How many git commits to look back at.'
    required: false
    default: '1'
  detect_num_commits_back:
    description: 'Whether or not it should auto-detect the number of commits to look back at.'
    required: false
    default: true
outputs:
  all_files_changed:
    description: 'All of the changed files.'
  added_files:
    description: 'Only files added.'
  copied_files:
    description: 'Only files copied.'
  deleted_files:
    description: 'Only files deleted.'
  modified_files:
    description: 'Only files modified.'
  renamed_files:
    description: 'Only files renamed.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.number_commits_back }}
    - ${{ inputs.detect_num_commits_back }}