name: Banned file changes (push)
on:
  push:
    branches: [ "**/*" ]
  
jobs:
  check_for_banned_file_changes:
    if: contains('snafu, timclegg', github.actor) == false
    name: Look for unsupported (banned) file modifications on PRs
    runs-on: ubuntu-latest
    steps:
      - name: Get all file changes
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Look for banned files
        if: contains(steps.files.outputs.all, '.github')
        run: |
          echo 'Changes to files in .github are not allowed.'
          exit 1