name: Banned file changes
on:
  pull_request:
    branches: [ "**/*" ]
  
jobs:
  check_for_banned_file_changes:
    name: Look for unsupported (banned) file modifications on PRs
    runs-on: ubuntu-latest
    steps:
      - name: Get file changes
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Look for banned files
        if: contains(steps.files.outputs.all, '.github')
        run: exit 1