name: Audit licenses
on:
  pull_request:
    branches: [ "**/*" ]

jobs:
  run_scancode_toolkit:
    name: Get inventory of licenses used in project
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/oracledevrel/scancode-toolkit:v21.3.31
      credentials:
        # username: ${{ github.actor }}
        # password: ${{ secrets.GITHUB_TOKEN }}
        username: ${{ secrets.PACKAGE_READ_USER }}
        password: ${{ secrets.PACKAGE_READ_SECRET }}
      volumes:
        - $GITHUB_WORKSPACE:/project
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Run Scancode-toolkit
        # uses: addnab/docker-run-action@v3
        # with:
        #   registry: ghcr.io/oracledevrel
        #   image: scancode-toolkit:v21.3.31
        #   # options:
        #   run: |
        #     scancode -clpeui --ignore licenses.json --json-pp /github/workspace/licenses.json /github/workspace/
        run: scancode -clpeui --ignore licenses.json --json-pp /project/licenses.json /project/
      - name: Commit updated licenses.json
        run: |
          git add licenses.json
      - name: Commit & push licenses.json
        uses: actions-js/push@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
          message: 'Updating licenses.json'