name: Audit licenses
on:
  pull_request:
    branches: [ "**/*" ]

jobs:
  run_scancode_toolkit:
    name: Get inventory of licenses used in project
    runs-on: ubuntu-latest
    container:
      image: txl8578/scancode-toolkit
      # image: ghcr.io/oracledevrel/scancode-toolkit:v21.3.31
      # credentials:
      #   username: ${{ github.actor }}
      #   password: ${{ secrets.GITHUB_TOKEN }}
      # volumes:
      #   - $GITHUB_WORKSPACE:/project
      volumes:
        - /__w/test/test:/project
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2
        # with:
        #   persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        #   fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Run Scancode-toolkit
        # uses: addnab/docker-run-action@v3
        # with:
        #   registry: ghcr.io/oracledevrel
        #   image: scancode-toolkit:v21.3.31
        #   # options:
        #   run: |
        #     scancode -clpeui --ignore licenses.json --json-pp /github/workspace/licenses.json /github/workspace/
        # run: scancode -clpeui --ignore licenses.json --json-pp /project/licenses.json /project/
        run: |
          scancode -l --ignore licenses.json --ignore ".github/**/*" --ignore "license_policy.yml" --license-policy /__w/test/test/license_policy.yml --only-findings --summary --json-pp /__w/test/test/licenses.json /__w/test/test/
          echo "\n\nHere are the licenses found:\n"
          echo $(cat licenses.json)
      - name: Look for non-approved licenses
        # run: |
        #   if (( grep -siHE '^[[:space:]]+"license_policy": \{\},$' licenses.json | grep -siHE '^[^[:blank:]].*' | wc -l > 1 ))
        #   then
        #     echo "ERROR: At least one non-approved license found.  Here are the matches:"
        #     echo $(grep -siHE '^[[:space:]]+"license_policy": \{\},$' licenses.json)
        #     exit 1
        #   else
        #     echo "All identified licenses are approved."
        #     exit 0
        #   fi
        uses: ./.github/actions/license_audit
        id: analysis
        with:
          licenses_file: '/github/workspace/licenses.json'
      - name: Analysis results
        run: echo "${{ steps.analysis.outputs.unapproved_licenses}}"
      # - name: Commit updated licenses.json
      #   run: |
      #     git add licenses.json
      # - name: Commit & push licenses.json
      #   uses: actions-js/push@v1.2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: 'main'
      #     message: 'Updating licenses.json'