name: Post-Pull Request Pipeline
on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  generate_changelog:
    if: ${{ github.event.pull_request.merged }} == true
    name: Generate changelog for the pull request
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2
      - name: "Make the changelog"
        uses: metcalfc/changelog-generator@v1.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}