name: Pre-Pull Request
on:
  pull_request:
    branches: [ "**/*" ]
  
jobs:
  run_repolinter:
    name: Run Repolinter on pull request
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2
      
      - name: 'Check against Repolinter'
        uses: newrelic/repolinter-action@v1
        with:
          config_file: 'repolinter.json'