name: RepoLinter
on:
  pull_request:
    # branches: [ "main", "**/*" ]
    # branches:
    #   - "main"
  # pull_request_review:
  pull_request_target:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_repolinter:
    name: Run Repolinter on pull request
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.event.pull_request.head.sha }}
      - name: "List directory"
        run: echo $(ls $GITHUB_WORKSPACE)
      
      # - name: 'Check against Repolinter'
      #   uses: newrelic/repolinter-action@v1
      #   with:
      #     config_file: 'repolinter.json'


          # config_url: https://raw.githubusercontent.com/aperture-science-incorporated/.github/master/repolinter-newrelic-communityplus.json
      
      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
      # - uses: 