name: Repolinter
on:
  pull_request:
    branches: [ "**/*" ]
  
jobs:
  run_repolinter:
    name: Run Repolinter on pull request
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v2
      
      - name: 'Check against Repolinter'
        id: repolinter1
        uses: newrelic/repolinter-action@v1
        with:
          config_file: 'repolinter.json'
          output_type: issue
          # username: my-token-username
          # token: ${{ secrets.MY_TOKEN }}
      
      - name: 'Check against Repolinter'
        id: repolinter2
        uses: newrelic/repolinter-action@v1
        with:
          config_file: 'repolinter.json'
      
      # - name: 'Output'
      #   run: |
      #     echo "${{ steps.repolinter.outputs.passed }}"
      #     echo "${{ steps.repolinter.outputs.errored }}"
      #     echo "${{ steps.repolinter.outputs.json_output }}"